### ISSUE TITLE
uanble to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by ghostjat** [v1cont/yad#10]
`./configure --enable-html --enable-gio --enable-spell --enable-sourceview --enable-icon-browser --with-gtk=gtk3
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether NLS is requested... yes
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/local/bin/intltool-update line 876.
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.
`
intltool 0.51.0 installed

**Comment by v1cont** [comment]
this is a bug in intltool. perl 5.21 requires to escape braces in regex. here is the fix

[intltool-perl.patch.gz](https://github.com/v1cont/yad/files/2053120/intltool-perl.patch.gz)
