### ISSUE TITLE
leading "-" (minus) in value breaks output

### ISSUE THREAD

**Issue by frostworx** [v1cont/yad#104]
Hi,
First of all great program, thanks a lot! 
Currently I'm implementing a yad settings menu in my [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch)
and noticed, that yad has problems with a leading "-" (minus) in variables, which breaks the whole config, as the entry is skipped and destroys the order of all config options. I workaround this, by adding a " " (space) before the minus in the variable directly in the yad command, which seems to work as it should. Here's a little example, which demonstrates the issue:
```
#!/bin/bash

CMDARGS="-leading -minus breaks"

yad --form --separator="\n" --quoted-output \
--text="<span font_weight='bold'>Settings for Game</span>" \
--field="commandline arguments" "$CMDARGS"

# with this parameter extension it works:
#--field="commandline arguments" "${CMDARGS/#-/ -}"

```
If there's anything else you need please tell me.

**Comment by v1cont** [comment]
simply add -- (two dashes) before $CMDARG

this is working

```
yad --form --separator="\n" --quoted-output \
    --text="<span font_weight='bold'>Settings for Game</span>" \
    --field="commandline arguments" -- "$CMDARGS"
```

**Comment by frostworx** [comment]
Oh my.... Thank you very much for your quick reply! *closing here*

**Comment by frostworx** [comment]
Sorry, closed it too early.
Indeed this works for one argument, but I have multiple and yad stops after the first one:
                                                                                  
```
#!/bin/bash

CMDARGS="-leading -minus breaks"
OTHERARGS="-second -of -multiple -lines"

yad --form --separator="\n" --quoted-output \
--text="<span font_weight='bold'>Settings for Game</span>" \
--field="commandline arguments" -- "$CMDARGS" \
--field="other arguments" -- "$OTHERARGS"
```

Would be great if you had a hint :)

**Comment by v1cont** [comment]
-- is a usual separator for options and arbitrary arguments. if some of your arguments started with dash, don't mix them with options. 

```
yad --form --separator="\n" --quoted-output \
--text="<span font_weight='bold'>Settings for Game</span>" \
--field="commandline arguments" --field="other arguments" \
-- "$CMDARGS" "$OTHERARGS"
```

**Comment by frostworx** [comment]
Great, that works (I knew double dash, but tbh I never ever had any real life need for it...)...
Thank you very much for your help! Very appreciated!

**Comment by henk717** [comment]
I'm currently running into the same issue with this one:
```
    OUTPUT=$(yad --form --center --window-icon=changes-allow --image=preferences-system --title="Configuration Utility | $VERSION" \
        --text="This will replace the configuration file with the provided settings" \
        --separator=$'\x1F' \
        --field="RDP Configuration":lbl --align=center "" \
        --field="Server" "$server" \
        --field="Domain" "$domain" \
        --field="Parameters" "$original_param" \
        --field="Dialog Configuration":lbl --align=center "" \
        --field="Admin Password":h "$adminpass" \
        --field="Helpdesk Contact" "$helpdesk" \
        --field="Login Timeout in Seconds" "$login_timeout" \
        --field="OS Configuration":lbl --align=center "" \
        --field="Speaker Volume" "$volume" \
        --field="Microphone Volume" "$microphone" \
        --field="Screen Brightness" "$brightness" \
        --field="Screen Standby Timeout in Seconds" "$screen_timeout" \
        --field="Keyboard Layout" "$keylayout" \
        --field="Exit Type (Shutdown/Sleep/Restart)" "$exit_type" \
        --field="Remote Configuration":lbl --align=center "" \
        --field="Remote Config Location" "$config_url" )
```
But my config screen is quite a bit bigger than the example above so I can't easily insert -- into it or half the options are missing.
Separating this out into multiple dialogs is not an option for me.

Why is anything between quotes not being treated like a value??

**Comment by v1cont** [comment]
this is a glib's commandline option parser restrictions. try to use temp file and --rest option for passing field values to the dialog

**Comment by v1cont** [comment]
```bash
#! /bin/bash

args=$(mktemp --tmpdir args.XXXXXXXX)
trap "rm -f $args" EXIT

cat > $args <<EOF
-one
-two
--three
EOF

yad --form --field=1 --field=2 --field=3 --rest=$args

```
