### ISSUE TITLE
Tooltip per Checkbox item?

### ISSUE THREAD

**Issue by frostworx** [v1cont/yad#106]
Hi,
I haven't found anything, so I guess the chances are low, but I'd like to ask if
it is possible to define a corresponding tooltip to every Checkbox (:CB or :CBE) item?
F.e. as source I have a list with
```
"short-stringA";"/some/absolute/path/with/unknown/length/but/in/any/case/too/long/as/box"
"short-stringB";"/another/absolute/path/with/unknown/length/but/in/any/case/too/long/as/box"
```
and I'd like to have the short string as selection and the long string as tooltip.
Any hint is very welcome!

**Comment by v1cont** [comment]
```yad --form --field 'shot!long description:chk'```

also you can redefine `!' separator for label and tooltip by setting --item-separator option

**Comment by frostworx** [comment]
Sorry, I didn't express correctly - I meant **ComboBox**.
I'd like to have a new tooltip for every single item which is currently active in the Dropdown Menu.

So with the above example **short-stringA** and **short-stringB** would be the visible items in the Dropdown Menu and
"/some/absolute/path/with/unknown/length/but/in/any/case/too/long/as/box"
and
"/another/absolute/path/with/unknown/length/but/in/any/case/too/long/as/box"
would be the corresponding tooltip *(depending on which is currently selected)*

Wouldn't be a big deal if this doesn't work, I just wanted to ask politely.
