### ISSUE TITLE
Feature Request: Allow Tabs to work under wayland

### ISSUE THREAD

**Issue by frostworx** [v1cont/yad#109]
Hello, @v1cont!
after a long time I tried wayland again yesterday _(IMHO it is not as urgent to deprecate X as it was provocatively claimed these days though)_ and noticed that yad Tabs do not work under wayland.
Instead every Tab opens its own requester which breaks the whole functionality.
Is it possible that you could add that function to yad _(TBH I have no clue how big this issue is 'under the hood')_?

Reproducable with this command:
` yad --plug=12345 --tabnum=1 --text="first tab with text" &> res1 &yad --plug=12345 --tabnum=2 --text="second tab" --entry &> res2 &yad --notebook --key=12345 --tab="Tab 1" --tab="Tab 2"`

directly copy/pasted from [the smokey01 examples here](http://smokey01.com/yad/)

Edit: just found that there's also a warning on stdout:
`WARNING: This mode not supported outside X11`
_(which has 1 (one!) google hit here: https://github.com/v1cont/yad/blob/master/po/uk.po )_

**Comment by sarether** [comment]
Have you tried running YAD with "GDK_BACKEND=x11"?
`GDK_BACKEND=x11 yad`

**Comment by frostworx** [comment]
Thanks, would have been a nice workaround indeed, but with x11 only the seconds tab opens.

**Comment by v1cont** [comment]
yad uses xembed for notebook and paned dialogs. this protocol is not available in native wayland

**Comment by frostworx** [comment]
Ah I see. Thanks for the explanation.

**Comment by frostworx** [comment]
I removed all tabs for the next release of my program and it works correctly under wayland now. So closing here.
