### ISSUE TITLE
When Clicking Buttons with odd numbers no data is returned

### ISSUE THREAD

**Issue by frostworx** [v1cont/yad#115]
Some buttons don't receive any data for no obvious reason in this example *(cut from my program and removed some variables)*. 
Only every second button returns the data.
Do I have a bug I do not see?
```
#!/bin/bash
yad --title="SteamTinkerLaunch-launchGameMenu" --image-on-top --notebook --form \
--button="BACK":0 --button="GUI SETS":1 --button="MENU SELECTION":2 --button="RELOAD":3 --button="SAVE":4 --button="SAVE AND PLAY":5 --button="PLAY":6 \
--field="('WAITEDITOR')":NUM "2" --field="('TOGGLEWINDOWS')":CHK "1" --scroll

echo "PRESSED $?"
```

**Comment by frostworx** [comment]
Still reproducable with this shorter version:
```
#!/bin/bash
yad --title="T" --form --button="BACK":0 --button="GUI":1 --button="MENU":2 --field="A":NUM "2" --field="B":CHK "1"
echo "PRESSED $?"
```

```
$ yad --version
7.3 (GTK+ 3.24.23)
```

**Comment by frostworx** [comment]
As mentioned in my linked issue I "fixed" the problem before by skipping "button 3" in another function.
So skipping all odd numbered buttons would be a valid *(but ugly)* workaround.

**Comment by frostworx** [comment]
Reproducible back to yad 4.0 (GTK+ 3.24.23) _(haven't tried older)_
Maybe the problem is directly in gtk then(?)

**Comment by frostworx** [comment]
The problem is directly in main.c
This line
https://github.com/v1cont/yad/blob/master/src/main.c#L889
excludes all odd numbered buttons.
If replacing
`else if (!(ret & 1))`
with
`else`
the problem is fixed!

_(the if else statement of course doesn't make any sense then, but idk what (!(ret & 1) should capture - numbers?)_

**Comment by frostworx** [comment]
`Even exit code mean to print result, odd just return exit code.`
from EXIT STATUS manpage.
That is unexpected imho.

**Comment by Botspot** [comment]
Same issue here. I've learned to reserve even-numbered buttons for positive actions, and odd-numbered buttons for things like exit, back, cancel, close, etc.

**Comment by v1cont** [comment]
use --always-print-result option for such cases

**Comment by frostworx** [comment]
good to know! thanks!
