### ISSUE TITLE
Simple text box - height algorithm

### ISSUE THREAD

**Issue by fdservices** [v1cont/yad#116]
This may be related to #107.

If I call a simple text box with <code> yad --image "dialog-warning" --undecorated --on-top --no-buttons --skip-taskbar --text "Text for message"</code> I get a nice text box like this:

![image](https://user-images.githubusercontent.com/3006039/101069891-e77e9380-359a-11eb-89e0-d2e84831e1e9.png)

However if I use <code>yad --image "dialog-warning"  --undecorated --on-top --no-buttons --skip-taskbar --text "Text for message with extra text"</code> then I get this, which is not so nice, much higher, and out of proportion. 

![image](https://user-images.githubusercontent.com/3006039/101069460-51e30400-359a-11eb-94aa-6ea8fdf71d4f.png)
I have tested using the geometry, width and height options, and the result is similar.

**Comment by eworm-de** [comment]
For me it looks like this with the last patch referenced in #107 applied.

**Comment by fdservices** [comment]
Agreed - closed in reference to #107
