### ISSUE TITLE
Dynamically update Gui elements depending on current CBE item possible?

### ISSUE THREAD

**Issue by frostworx** [v1cont/yad#121]
Sorry for another question, but I haven't found anything into that direction.

Is something like this currently possible?:
```
#!/bin/bash
SELECT=3
TEXT="text for $SELECT"
SHOWPIC="/tmp/pic_${SELECT}.jpg"
yad --image "$SHOWPIC" --image-on-top --form --text="$TEXT" --field="select":CBE "${SELECT}!1!2!3"
```
So using the currently selected item (here number) for dynamically updating the shown text and picture belonging to the item?
Would be great to have such a feature.

**Comment by v1cont** [comment]
sorry,  this is not possible right now. i'll plan to implement a limited set of action handlers with remote control to yad in future releases, but cannot say an approximate date when it will be available

**Comment by frostworx** [comment]
Thanks a lot for the reply! Your plans sound very interesting, whenever you find the time I'll be happy to play with it!
Congratulations on v8.0! Great work! :)
