### ISSUE TITLE
Irregular icon size in list dialog

### ISSUE THREAD

**Issue by magpie514** [v1cont/yad#129]
I'm using yad (built locally from https://github.com/v1cont/yad/commit/6b2d263d4df9408e1f99b5fc1b0834dca8f48534 , although the issue started a few days ago) in Ubuntu 20.10 64b. I have a little script to have a list of template files, not unlike the create new file menus in Explorer.
But a few days ago this...oddity started appearing.
![CopyQ uzzXtp](https://user-images.githubusercontent.com/323651/115126491-a1692000-9fcf-11eb-8e2d-4a7d5121f0e6.png)
The anomalously large icon was fine by the start of the month, and I didn't change the script for a while, so I wonder if this is some sort of regression.

Please let me know if any extra information is required.

The code used to produce this window is as follows:
```bash
#!/usr/bin/env bash

function main {
	local dest_dir="$1"
	local n=0
	[[ ! -d $dest_dir ]] && { echo "Destination path does not exist." ; exit 1; }
	[[ ! -w $dest_dir ]] && { echo "Destination path is not writable."; exit 2; }
	local templates_dir="$HOME/Documents/Templates/"
	local templates=""
	local sep=""
	for i in "$templates_dir"/*; do
		templates+="$sep$(gio info -a standard::icon "$i" | awk '/standard::icon/{print $2}' | sed 's/,//') $(basename "$i")"
		sep="\n"
	done
	local list;list=$(echo -e "$templates")
	echo "$list"
	local dest_file;dest_file="$(yad --title=Templates --window-icon=template --height=480 --width=300 --image=template\
	--text="Select template..." --center --on-top --undecorated --separator=""\
	--list --no-headers --column="1:IMG" --column="2:TXT" --search-column="2" $list 2> /dev/null)"

	[[ -z $dest_file ]] && { echo "Cancelled."; exit 3; }

	local dest_path="$dest_dir/$dest_file"

	[[ -f $dest_path ]] && {
		echo "$dest_path exists. Renaming..."
		n=1
		while [[ -f "$dest_dir/${dest_file%.*}(${n}).${dest_file##*.}" ]] ; do
			(( n++ ))
		done
		dest_path="$dest_dir/${dest_file%.*}(${n}).${dest_file##*.}"
	}

	echo "Copying template to $dest_path."
	cp "$templates_dir/$dest_file" "$dest_path"
}

main "$@"
```

**Comment by v1cont** [comment]
is this icon looks same in yad-icon-browser? and what the output of ```yad-tools --icon --size=16 <icon-name>```?

**Comment by magpie514** [comment]
Apparently no, it shows normally in the icon browser, and output of yad-tools is "$HOME/.local/share/icons/Papirus-Dark/16x16/categories/draw.io.svg", which seems normal.
![image](https://user-images.githubusercontent.com/323651/115148880-c60dd800-a061-11eb-9e8b-88d48565cbd2.png)

**Comment by v1cont** [comment]
try to add ```--icon-size=16 --keep-icon-size``` options

**Comment by v1cont** [comment]
and may you send me this icon by e-mail or attach it here?

**Comment by magpie514** [comment]
No change with those extra options, it seems.
![image](https://user-images.githubusercontent.com/323651/115149016-5fd58500-a062-11eb-8c4d-db7e1febfc5e.png)

Here is the icon in question:
[draw.io.zip](https://github.com/v1cont/yad/files/6331457/draw.io.zip)

**Comment by v1cont** [comment]
thank you

**Comment by v1cont** [comment]
please check latest git

**Comment by magpie514** [comment]
Strange, it's still doing it, with the extra options or without.
![image](https://user-images.githubusercontent.com/323651/115462841-6bc07300-a22b-11eb-92cc-681ce02e5929.png)
Building went fine and all files are proper. 
Looking at it closer, that icon is installed in $HOME/.local/share, since the tool is an appimage instead of a proper install. That seems to reflect in the icon name:
![image](https://user-images.githubusercontent.com/323651/115463476-2486b200-a22c-11eb-85da-5fbea1551241.png)
Could this difference be the culprit?

**Comment by v1cont** [comment]
yad forced to scale image only if icon specified by name. a full path to file means that image shows without changes

**Comment by magpie514** [comment]
So the problem would be caused by `gio` giving a filename instead of an icon name?
