### ISSUE TITLE
No working --notification --tooltip

### ISSUE THREAD

**Issue by Alexandr1322** [v1cont/yad#133]
Hi, I can't change the tooltip for the icon.
Try --tooltip="blablabla" --tooltip=blablabla --tooltip "blablabla"
Debian 10 version yad 0.40
Archlinux version yad 10.1
The inscription " YAD" doesn't change.

**Comment by phenixia2003** [comment]
Hi,

You must use the option --text to set the notification tooltip text :

`yad --notification --text="notification tooltip text"`

**Comment by v1cont** [comment]
is that behavior reproducible in a git version?
