### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by darkhz** [v1cont/yad#161]
A double free is triggered when invoking yad with the following sequence of command and keystrokes (**text in between `<` and `>` should be interpreted as keystrokes**)

```bash
yad --notification --listen <Enter>
action: <Enter>
action  <Enter>
action: <Enter>
```

The output suddenly returned is:
`free(): double free detected in tcache 2`

and yad is closed with a SIGABRT.

The issue seems to point to this [line](https://github.com/v1cont/yad/blob/f14f5fc497827871e314c5c7b68d12a4de827d46/src/notification.c#L348). A possible solution could be to invoke g_free only after a value has been found.

**Comment by darkhz** [comment]
cc @v1cont

**Comment by v1cont** [comment]
though i cannot reproduce it you are right, such behavior is possible. please check de594b6

**Comment by darkhz** [comment]
Yes, this issue is fixed with the commit. Thank you.
