### ISSUE TITLE
yad --color missing eyedropper/color picker

### ISSUE THREAD

**Issue by bdantas** [v1cont/yad#164]
_yad --color_ used to bring up a color selection box that included an eyedropper/color picker. (I'm talking about the tool that allows the user to click on a pixel somewhere on the screen, then the color dialog displays the color code for that pixel.) Without the eyedropper, the color selection box is not as useful (to me it is useless, actually). Would it be possible to bring back the eyedropper?

**Comment by v1cont** [comment]
added in ffd6979

**Comment by bdantas** [comment]
Thank you for adding this feature back in!

**Comment by bdantas** [comment]
I compiled yad version 12 but still don't see the eyedropper when I run "yad --color". Am I missing something?
![screenshot1_small](https://user-images.githubusercontent.com/5084088/166502929-2dde3e1f-0514-4d21-99e7-d444b155d8b2.jpg)

**Comment by v1cont** [comment]
```yad --color --picker```. this option adds picker button at the bottom of a dialog

**Comment by v1cont** [comment]
and also you can try ```yad-tools --color --pick```

**Comment by bdantas** [comment]
Yes, it works exactly as advertised. Thank you and sorry for the noise.
