### ISSUE TITLE
Feature Request: add --listen to --list in addition to --notification

### ISSUE THREAD

**Issue by manoflinux** [v1cont/yad#179]
Sorry if this is the wrong place to post this, I usually just interact with my teams code. 
But adding --listen and some commands to --list  to update the columns and text would be very useful.
Unlike some of the other dialogs --list seems to be much more resizable, making it very useful for what I want. .
What I would like to do with it is make a monitor that sits on my desktop and receives various inputs and displays them using the listening yad --list instance.

**Comment by v1cont** [comment]
--listen option for --list dialog already exist a long time. what version of yad you use?

**Comment by manoflinux** [comment]
Thanks.
I tried it again, and I am not sure what I was doing wrong last time, but its kinda working now. 
But the problem is it just adds columns when I send it something, what command do I send it to update a column. 
I have a column called "text" and I tried this command and nothing changes.
echo 'text:TESTING'>/tmp/bash.xwgKZ0Qa
But when I did this, I get an new entry in that column saying icon:NEWTEXT
echo 'icon:NEWTEXT'>/tmp/bash.xwgKZ0Yetemper

So how do I send a command to update a specific entry in that column?
Sorry I can't find any documentation or examples for using --listen with --list, only stuff on --notification

**Comment by v1cont** [comment]
you cannot change single cell in the existing grid but you can clear the whole list by sending '\f' and than add a new stuff

```bash
( echo "first entry text" ; sleep 5 ; echo -e '\f' ; echo "next entry text" ) | yad --list --column=tst
```

**Comment by manoflinux** [comment]
thanks! I was coming here to say I re-read the manpage and found that out. 
Sorry for reporting bugs that were just me not reading the man page well enough!
