### ISSUE TITLE
--button icon regression

### ISSUE THREAD

**Issue by step-** [v1cont/yad#185]
Comparing [yad_gtk2](https://github.com/step-/yad) with [master](https://github.com/v1cont/yad/tree/04167716187efd7e63bb78e4a3f878c673ea99c6) the following commands show what seems to be a regression when a label is included in the button spec.
```sh
# show regression (top right in screenshot)
# I expected to see the yad-no icon
yad_gtk2 --button='gtk2!gtk-yes!tooltip:xdg-open .' & yad --button='master!yad-no!tooltip:xdg-open .' &

# show parity (bottom row in screenshot)
# both yads show their respective button icon + stock label
yad_gtk2 --button='gtk-yes:xdg-open .' & yad --button='yad-no:xdg-open .' &
```

![yad-20220713](https://user-images.githubusercontent.com/1414102/178714188-95e1ca5b-b880-4d1c-a674-c6f5c93ae050.png)

**Comment by Misko-2083** [comment]
It's not a regression see here [L45](https://github.com/v1cont/yad/blob/master/src/util.c#L45)
yad_stock_items have a label and an image.
yad-no is equivalent to "No!gtk-no"
so this will work
```C
yad --button='master!gtk-no'
```
