### ISSUE TITLE
Gtk-WARNING: '-gtk-icon-size' is not a valid property name

### ISSUE THREAD

**Issue by sonic2kk** [v1cont/yad#231]
## System Information
OS: Arch Linux with KDE Plasma 5.27.4
Graphics Platform: Wayland
Yad version: 12.3 (GTK+ 3.24.37)

## Overview
I recently updated my KDE Plasma version and I suppose along with it there were perhaps some GTK updates. Whenever I run Yad now, even just `yad`, I get the following warning:

```
(yad:88194): Gtk-WARNING **: 23:15:09.263: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
```

When searching to see if this had been reported before or patched already, I found #138 from just under 2 years ago, which mentions that `-gtk-icon-size` was deprecated. Perhaps now it has been removed, and results in this GTK warning.

I checked to make sure there wasn't any custom GTK CSS being set on my system which could raise this, and didn't find anything.

<hr>

This isn't breaking anything as far as I can tell. I maintain a program which heavily utilises Yad and have not seen any change in behaviour. Regardless, I thought it might be useful to bring it up. Then at the very least if other users see this warning and look it up, they should hopefully come across this issue.

**Comment by v1cont** [comment]
this is issue of your gtk theme

**Comment by sonic2kk** [comment]
I guess it's an upstream KDE issue then (I'm just using Breeze), I'll close this and report it to the KDE bug tracker when I have some time. Thanks!
