### ISSUE TITLE
[Question] How could a value for `--plug`/`--key` be generated ?

### ISSUE THREAD

**Issue by KaKi87** [v1cont/yad#260]
If I use `date +%s%3N` (number of milliseconds since Epoch) for example, I get the following error :

```
Unable to parse command line: Integer value “” for --plug out of range
```

Thanks

**Comment by tspier** [comment]
Have you tried using **KEY=$RANDOM** and then referring to it with **yad --plug=$KEY**?

**Comment by v1cont** [comment]
you can use $RANDOM, $!, $$ or any arbitrary value getting from rolling dices. the only condition - the value must be positive signed integer and same for all embedded dialogs

**Comment by KaKi87** [comment]
Very well, thanks !
