### ISSUE TITLE
File/Directory Selection with Specific Directory as start

### ISSUE THREAD

**Issue by tokenwizard** [v1cont/yad#264]
I'm trying to figure out if there is a way to launch with the `--file` mode but start in a specific directory. It seems by default it starts with the "Home" folder: 
![image](https://github.com/v1cont/yad/assets/24832561/52be5ab4-7748-4d28-bdf7-fde30b883600)

I was hoping for a way to pass a folder as an argument, something like below, and have the file/directory selection dialog box open to that location:
`yad --file ~/Pictures`

**Comment by v1cont** [comment]
default is current working directory

so try

```
pushd ~/Pictures
yad --file 
popd

```

On Tue, 11 Jun 2024 11:31:02 -0700
tokenwizard ***@***.***> wrote:

> I'm trying to figure out if there is a way to launch with the `--file` mode but start
> in a specific directory. It seems by default it starts with the "Home" folder:
> ![image](https://github.com/v1cont/yad/assets/24832561/52be5ab4-7748-4d28-bdf7-fde30b883600)
> 
> I was hoping for a way to pass a folder as an argument, something like below, and have
> the file/directory selection dialog box open to that location: `yad --file ~/Pictures`
> 
> 
> 
> 



-- 
wbr

Victor Ananjevsky, ***@***.***>

**Comment by tokenwizard** [comment]
Ok, that seems to work. What is the significance of the `popd` command above? 
```pushd ~/Documents
yad --file
```
works just fine.

Unfortunately `pushd ~/Documents | yad --file` does not, but that's not a big deal.
