### ISSUE TITLE
Build fail on Debian 12

### ISSUE THREAD

**Issue by Xdavius** [v1cont/yad#269]
Hi

This error occur while trying to build on Debian 12 only :

```
CCLD     yad-icon-browser
/usr/bin/ld: yad-list.o: in function `get_data_as_string':
/tmp/pacstall/yad~14.0/yad-14.0/src/list.c:759: undefined reference to `g_string_free_and_steal'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:487: yad] Error 1
make[2]: Leaving directory '/tmp/pacstall/yad~14.0/yad-14.0/src'
make[1]: *** [Makefile:403: all-recursive] Error 1
make[1]: Leaving directory '/tmp/pacstall/yad~14.0/yad-14.0'
make: *** [Makefile:344: all] Error 2
```

Any idea to solve this?

Regards

**Comment by Pro-pra** [comment]
g_string_free_and_steal was introduced in GLib 2.75.3, released 2023-02-13

**Comment by step-** [comment]
@Xdavius try getting the patch file for 1153a3e, apply the patch and rebuild. It worked for me for the same error message.

**Comment by Xdavius** [comment]
> @Xdavius try getting the patch file for [1153a3e](https://github.com/v1cont/yad/commit/1153a3e6105a21597454e3835cfb96ea59b330f5), apply the patch and rebuild. It worked for me for the same error message.

Thank you ! works on all builds.

https://github.com/pacstall/pacstall-programs/pull/6184

Closing.
