### ISSUE TITLE
New versions fails to compile

### ISSUE THREAD

**Issue by Thanatermesis** [v1cont/yad#270]
```text
/usr/bin/ld: yad-list.o: in function `get_data_as_string':
./src/./src/list.c:759: undefined reference to `g_string_free_and_steal'
```

OS: Debian Stable (12 / Bookworm)

**Comment by step-** [comment]
See #269.

**Comment by Thanatermesis** [comment]
I see
So is already fixed? 🤔 mmh, that's because my packager is based on "tags" (it rebuilds yad from every new tag version found, not from every commit)

**Comment by v1cont** [comment]
done
