### ISSUE TITLE
--window-icon switch don't display any icon

### ISSUE THREAD

**Issue by sputnick-dev** [v1cont/yad#281]
I use:

    yad --window-icon /path/to/file.png --question --title comment

This was working on a previous version, but now nothing.

The file can be opened with the same user running `yad`.

I use LinuxMint Wilma xfce4 and `yad 10.90 (GTK+ 3.24.30)`

The PNG icon: 
![reddit](https://github.com/user-attachments/assets/59ce9035-446a-4bc7-8cc2-a8478b37f02c)

**Comment by step-** [comment]
Option `--question` is invalid for yad, but it is valid for zenity.  Are you sure you weren't using zenity before?
Yad version 10.9 is quite old. The latest yad version is 14.1. However, upgrading won't add option `--question`.

**Comment by sputnick-dev** [comment]
`yad` simply ignore --question, thanks for the tip, but this is not the issue there.

question is the default.

My issue is about icon.

**Comment by step-** [comment]
I see. I downloaded your icon and tested it in yad 14.0 with this command `yad --window-icon /tmp/icon.png --title comment` and it worked for me. The icon is displayed in the window title bar, which is managed by your window manager (openbox, in my case).

**Comment by step-** [comment]
PS It isn't quite true that yad simply ignores `--question`. Yad will ignore invalid options only if it's configured to do so otherwise it will stop without displaying the dialog. See the "ignore unknown command-line options" checkbox in the `yad-settings` command.

**Comment by sputnick-dev** [comment]
Now:

```
$ yad --version
14.1 (GTK+ 3.24.41)
```

Still no icon. Any way to have it with `xfce4` ?

**Comment by step-** [comment]
> Still no icon. Any way to have it with xfce4 ?

Don't know, don't have xfce4. Maybe a question for the Mint forums?

**Comment by sputnick-dev** [comment]
`xfce4` forum, no? You think `LinuxMint` is more accurate?

**Comment by step-** [comment]
Ask both forums, no?

**Comment by sputnick-dev** [comment]
Solution: 

```
echo 'show_app_icon=true ' >> /usr/share/themes/$(xfconf-query -c xfwm4 -p /general/theme)/xfwm4/themerc
```
