### ISSUE TITLE
yad notebook parameter --active-tab

### ISSUE THREAD

**Issue by terminologie-x** [v1cont/yad#33]
yad --version
0.40.0 (GTK+ 3.24.4)

hi Victor,
hopefully you can read this :-)
already posted this bug in the ticketsystem at sourceforge, anyway let's say I want to start a script.sh with a parameter, yad should open the notebook with the initial active-tab 2. The following code should work:

#!/bin/bash -xv
id="${RANDOM}"
active_tab="$1"

yad --plug=$id --tabnum=1 --form --columns=4 --scroll --borders=30 &
yad --plug=$id --tabnum=2 --form --columns=4 --scroll --borders=30 &
yad --plug=$id --tabnum=3 --form --columns=4 --scroll --borders=30 &
yad --notebook --key="$id" --tab="tab1" --tab="tab2" --tab="tab3" --active-tab="$active_tab" --width=900 --height=600

If you test this script with ./script.sh 2 it should open the notebook with the initial tab2. In this case, it opens the first tab - always. So I assume, that the notebook parameter --active-tab, which was integrated in yad Version 0.39.0, is not working at all.

The notebook active tab function works with gtkdialog, an example is shown here:
http://blogs.czapski.id.au/2017/05/gtkdialog-exploring-the-notebook-object-by-example

In this example you can define which tab should be the initial active tab in the notebook widget.

Since i don't want to use gtkdialog or both tools with gtkdialog as a wrapper, i would appreciate it if you could at least confirm this bug in the actual yad version.

thanks in advance

**Comment by v1cont** [comment]
fixed - https://github.com/v1cont/yad/commit/90284629d95dc5940202d892631fe7add5833715
