### ISSUE TITLE
Application will not start

### ISSUE THREAD

**Issue by f0086** [v1cont/yad#34]
After launching yad (version 0.41.0), I got the following dialog:

![image](https://user-images.githubusercontent.com/121972/52538754-ae967e80-2d76-11e9-9f68-c56bcf219cc6.png)

No matter what button I press, the application exits.
This warning will be shown on STDERR:

```
(yad:20006): Gtk-WARNING **: 20:58:45.559: Error loading icon from file 'yad':
	Couldn’t recognize the image file format for file “yad”
```

I compiled the source with the following flags:

```    ./configure \
      --prefix=/usr \
      --with-gtk=gtk3 \
      --enable-icon-browser \
      --enable-html \
      --enable-gio \
      --enable-spell \
      --enable-sourceview
```

It does not make a difference if I use gtk2 or gtk3.

**Comment by v1cont** [comment]
so what you expect? yad always exits after pressing button with appropriate exit status.
warning rises because you launch yad from src directory. it contain file named 'yad' (this is default icon name) and yad itself search named image file for icon before asking for it to the icon theme
