### ISSUE TITLE
[Feature] extend icon resizing (--icons --icon-width) to compact list mode

### ISSUE THREAD

**Issue by step-** [v1cont/yad#35]
I'm opening this feature request as a follow up to PR #29, which is closed.

Victor, thank you for the feature in #29 6239dcf. It works very well for the grid layout. I wonder why you chose not to implement it also for the icon list (--compact) layout. I think it would be useful also in that case. Look at the screen shot below: yad 6239dcf --icon-size=32 --compact. The icons in /usr/share/pixmaps have different sizes so yad displays them at different sizes.  It would look much better, and more compact, if yad resized those icons the same size. And that is a _user-specified_ size.
So would you please make --icon-size work for --compact mode, too?
![yad-20190214-002](https://user-images.githubusercontent.com/1414102/52814251-f4678580-309b-11e9-9179-40717fd42261.png)

_Originally posted by @step- in https://github.com/v1cont/yad/pull/29#issuecomment-463777091_

**Comment by v1cont** [comment]
https://github.com/v1cont/yad/commit/b2355b8e4eb546297f0a7940d697abe1cbdf6a4e

**Comment by step-** [comment]
Hi Victor, I tested commit b2355b8 (gtk2 build only) but I don't see a change. What I had in mind was for the icon list to display equally-sized icons with a size that the user can choose, just like for the icon box, with --icon-size. There are still cases where the icons aren't equally sized.  If I specify icons as _theme icons_ then they are equally sized but all very small; --icon-size is ignored. If I specify icons as _icon paths_ the icons are bigger but unequally sized.  Please take a look at the screen shots and at the attached test script **[test-35.tar.gz](https://github.com/v1cont/yad/files/2873494/test-35.tar.gz)**. Thank you.

![yad-20190217-001](https://user-images.githubusercontent.com/1414102/52920339-b1134e00-330b-11e9-8938-4dc364af2241.png)

![yad-20190217-002](https://user-images.githubusercontent.com/1414102/52920349-bf616a00-330b-11e9-8b3e-6612782515e8.png)

**Comment by step-** [comment]
Hi Victor, I tested commit [b2355b8](https://github.com/v1cont/yad/commit/b2355b8e4eb546297f0a7940d697abe1cbdf6a4e) (gtk2 build only) and I can confirm that now the icon list displays equally-sized, small icons, and ignores --icon-size.  This is consistent with the help file entry so I'm closing this issue. Thanks.
