### ISSUE TITLE
Yad notification, left click menu

### ISSUE THREAD

**Issue by s3idani** [v1cont/yad#36]
My notification menu is working well at the right click (with icons and cmd). I would like to move it in the left click!! is this possible?

**Comment by v1cont** [comment]
https://github.com/v1cont/yad/commit/965c86e4f7ef95439ea5aa16540cb8e184d77881

Just set --action=menu and popup menu will be available on a left click in addition to traditional right click

**Comment by dshoreman** [comment]
@v1cont Thanks for adding this! If I use `echo "action:menu" >&3` in conjunction with `--listen`, I do get the menu on left click but it requires the mouse button to be held down (opposite to how the right-click menu works).

Is there any way of having the menu stay visible after mouse-up? Currently if I left-click the icon, the menu simply flashes for a split-second before disappearing again. I do kind of like the behaviour for a quick *click and drag* to select, but I can see it being confusing when it disappears on a normal click.
