### ISSUE TITLE
no menu icons in LXQt

### ISSUE THREAD

**Issue by bdantas** [v1cont/yad#41]
I'm on OpenBSD 6.4 with LXQt 0.13.0 and yad 0.40.0

Notification icon shows up fine, but no icons next to right-click menu items. For example, running this...

`yad --notification --image="dialog-error" --menu='Test!quit!dialog-error'`

...causes the dialog-error icon to show up in the system tray, but no icon at all next to the "Test" menu item.

P.S. On a different machine with OpenBSD and MATE, yad's menu icons show up without issue. But LXQt is my main DE, so I would like to find a fix or workaround for the missing menu icons in LXQt. Is yad butting heads with Qt? Maybe yad needs a gtk-related environmental variable that is missing in LXQt's environment? Icon theme issue? I've checked all of these to the best of my ability but I'm going around in circles because GUI intricacies are not my forte.

**Comment by catb0t** [comment]
any warnings/errors logged in the console / system logs?

**Comment by bdantas** [comment]
Nothing in the console or in ~/.xsession-errors. Interestingly, this shows up in ~/.config/lxqt/debug.log:

`2019-04-11 22:05:14.033 (0x7f7fffff1070) Warning:     * Error image is NULL`

This this suggest a problem/fix to you?

**Comment by bdantas** [comment]
I just needed to install lxappearance then, in that application, choose a gtk theme and check "use icons in menus".
https://forum.lxqt.org/t/yad-system-tray-woes/696
