### ISSUE TITLE
timeout-indicator no longer working - missing schema key

### ISSUE THREAD

**Issue by tonypaulic** [v1cont/yad#50]
`yad --question --timeout-indicator=top --timeout=15 --text "now?"`

... generates:

> (yad:14160): GLib-GIO-ERROR **: 18:15:23.606: Settings schema 'yad.settings' does not contain a key named 'show-remain'
> Trace/breakpoint trap (core dumped)

Adding the following key to the yad.gschema.xml file fixes the issue:

    <key type="b" name="show-remain">
      <default>true</default>
      <summary>Remaining time progress bar</summary>
    </key>

**Comment by v1cont** [comment]
fixed in 6b180f2
