### ISSUE TITLE
--fontname doesn't seem to work for --text-info

### ISSUE THREAD

**Issue by nicklan** [v1cont/yad#62]
No matter what I specify for `--fontname`, yad seems to use my default gtk3 font.

For example:
`yad --fontname="Webdings" --text-info --text="foo"`

Produces: 
![yad-ss](https://user-images.githubusercontent.com/178912/70196418-de2bc400-16c5-11ea-942f-ac1396de89e6.png)

**Comment by v1cont** [comment]
fixed in 4b54d14
