### ISSUE TITLE
Column text does not render markdown / yad version Fedora 0.40.0 6.fc31

### ISSUE THREAD

**Issue by dreamstorpi** [v1cont/yad#77]
`yad --list
--column "<span foreground='green' font-size='large' font='bold'>Pick one</span>"`

does not render the markdown as expected. 

No errors thrown. 

The column header becomes, `"<span foreground='green' font-size='large' font='bold'>Pick one</span>"`

Is this a bug or a version issue?

**Comment by v1cont** [comment]
column headers doesn't support markup

**Comment by dreamstorpi** [comment]
OK, thanks Victor.

Could this be an enhancement request?

**Comment by v1cont** [comment]
yes, it's a pretty nice idea and i implement it in a near future

**Comment by v1cont** [comment]
done in 902e519
