### ISSUE TITLE
Is it possible to add tooltip on --field, any type?

### ISSUE THREAD

**Issue by dreamstorpi** [v1cont/yad#79]
Hello, I am trying to add a tooltip to a --field (any type) definition, but I haven't found a way to it. 

Is it me? or is this not possible?

**Comment by v1cont** [comment]
this is impossible right now

how do you see this feature? it must be a tooltip on fields label or on a whole field?

**Comment by dreamstorpi** [comment]
Ideally, I see this feature as being able to hover the cursor over the field and the tooltip appears. 
Fields don't always have a label, so hovering in the field itself would cover all cases.
But if this is not possible, then hovering over the label would be better than nothing at all.

**Comment by v1cont** [comment]
added in 8bfcaf9

**Comment by dreamstorpi** [comment]
Thank you Victor.
Just tested - it works great.

For people reading this thread, you can enable tooltips on fields by using the format
--field LABEL!TOOLTIP:TYPE
