### ISSUE TITLE
Program returns random data in a function

### ISSUE THREAD

**Issue by katodev** [v1cont/yad#8]
At the end package building process I go the following error:

I: Program returns random data in a function
E: yad no-return-in-nonvoid-function option.c:1130, 1137, 1196, 1203, 1213

For the compiler there are warning only.

I could fix it with this patch:
--- src/option.c.orig	2017-11-16 20:13:51.000000000 +0100
+++ src/option.c	2017-12-02 22:15:59.718429232 +0100
@@ -1127,6 +1127,8 @@
 {
   options.data.use_posx = TRUE;
   options.data.posx = atol (value);
+
+  return TRUE;
 }
 
 static gboolean
@@ -1134,6 +1136,8 @@
 {
   options.data.use_posy = TRUE;
   options.data.posy = atol (value);
+
+  return TRUE;
 }
 
 static gboolean
@@ -1193,6 +1197,8 @@
     options.hscroll_policy = pt;
   else
     options.vscroll_policy = pt;
+
+  return TRUE;
 }
 
 #if GLIB_CHECK_VERSION(2,30,0)
@@ -1200,6 +1206,8 @@
 set_size_format (const gchar * option_name, const gchar * value, gpointer data, GError ** err)
 {
   options.common_data.size_fmt = G_FORMAT_SIZE_IEC_UNITS;
+
+  return TRUE;
 }
 #endif
 
@@ -1210,6 +1218,8 @@
   options.print_xid = TRUE;
   if (value && value[0])
     options.xid_file = g_strdup (value);
+
+  return TRUE;
 }
 
 static gboolean

**Comment by v1cont** [comment]
thank you, fixed
