### ISSUE TITLE
Debian 10.4 - fail to compile

### ISSUE THREAD

**Issue by Nerun** [v1cont/yad#84]
Whats wrong?
I got m4, libtool, libcurl4-openssl-dev, intltool, autotools, autoconf, automake...
![YADerror](https://user-images.githubusercontent.com/3987342/82620639-6720b400-9baf-11ea-894c-3869811d3469.png)

**Comment by v1cont** [comment]
check if libglib2.0-dev is installed

**Comment by Nerun** [comment]
GENIUS! Thank you!
![yaddone](https://user-images.githubusercontent.com/3987342/82667322-ffe61c80-9c0d-11ea-931f-a5001b9bf6b0.png)

**Comment by Nerun** [comment]
My package!

Please remove end ".zip" and just rename it to ".deb".

[yad_6.0-1_amd64.zip](https://github.com/v1cont/yad/files/4671776/yad_6.0-1_amd64.zip)
