### ISSUE TITLE
wrong dialog size

### ISSUE THREAD

**Issue by step-** [v1cont/yad#9]
Between 0660417 and 30a7c2f some change broke the dialog sizing for (my) GTK2 builds. Now the dialog is smaller that the `--button`s inside it so some buttons aren't visible. (Linux 64).  I need to review all your changes and figure out what's going on, but it will take some time before I can do it. If you already suspect some commits in particular, please let me know which ones. Thank you.

30a7c2f
![tas-20180508-075306](https://user-images.githubusercontent.com/1414102/39740394-f13a72e6-5284-11e8-9114-5d5d923d2021.png)

0660417
![tas-20180508-075343](https://user-images.githubusercontent.com/1414102/39740436-1cc06b50-5285-11e8-8c5c-f3545574369d.png)

**Comment by v1cont** [comment]
please check out latest version

**Comment by step-** [comment]
The latest commit efa8acf works well for me. I don't see the problem that I described anymore. Thank you very much, Victor.
