### ISSUE TITLE
Loop that can be broken

### ISSUE THREAD

**Issue by shlyakpavel** [v1cont/yad#92]
https://github.com/v1cont/yad/blob/c78baef50bd9fe6c58e923438e9cab90b0e82baf/src/list.c#L574
PVS studio static analysis tool has got a warning here: 

> V712 Be advised that compiler may delete this cycle or make it infinity. Use volatile variable(s) or synchronization primitives to avoid this.
See details at https://www.viva64.com/en/w/v712/

**Comment by shlyakpavel** [comment]
The same here https://github.com/v1cont/yad/blob/c78baef50bd9fe6c58e923438e9cab90b0e82baf/src/main.c#L597

**Comment by shlyakpavel** [comment]
And here https://github.com/v1cont/yad/blob/c78baef50bd9fe6c58e923438e9cab90b0e82baf/src/progress.c#L57

**Comment by shlyakpavel** [comment]
And here https://github.com/v1cont/yad/blob/c78baef50bd9fe6c58e923438e9cab90b0e82baf/src/text.c#L273

**Comment by v1cont** [comment]
maybe they are right. empty loops is not a good style, so i corrected this

**Comment by shlyakpavel** [comment]
Thanks
